const data = [
  {
    id: "001",
    name: "Bulbasaur",
    img: "/img/bulbasaur.png",
    type1: "Grass",
    type2: "Poison",
    weight: "6,9 kg",
    height: "0,7 m",
    ability1: "Chiorophys",
    ability2: "Overgrow",
    color1: "#74CB48",
    color2: "#A43E9E",
    description:
      "There is a plant seed on its back right from the day this Pokémon is born. The seed slowly grows larger.",
    stats: {
      HP: "045",
      ATK: "047",
      DEF: "047",
      SATK: "065",
      SDEF: "065",
      SPD: "045",
    },
  },
  {
    id: "004",
    name: "Charmander",
    img: "/img/charmander.png",
    type1: "Fire",
    type2: "",
    weight: "8,5 kg",
    height: "0,6 m",
    ability1: "Mega-Punch",
    ability2: "Fire-Punch",
    color1: "#F57D31",
    color2: "",
    description:
      "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    stats: {
      HP: "037",
      ATK: "052",
      DEF: "043",
      SATK: "060",
      SDEF: "050",
      SPD: "065",
    },
  },
  {
    id: "007",
    name: "Squirtle",
    img: "/img/squirtle.png",
    type1: "Water",
    type2: "",
    weight: "9,0 kg",
    height: "0,5 m",
    ability1: "Torrent",
    ability2: "Rain-Dish",
    color1: "#6493EB",
    color2: "",
    description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
      HP: "044",
      ATK: "047",
      DEF: "065",
      SATK: "050",
      SDEF: "064",
      SPD: "043",
    },
  },
  {
    id: "012",
    name: "Butterfree",
    img: "/img/butterfree.png",
    type1: "Bug",
    type2: "Flying",
    weight: "32,0 kg",
    height: "1,1 m",
    ability1: "Compound-Eyes",
    ability2: "Tinted-Lens",
    color1: "#A7B723",
    color2: "#A891EC",
    description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
      HP: "060",
      ATK: "045",
      DEF: "050",
      SATK: "090",
      SDEF: "080",
      SPD: "070",
    },
  },
  {
    id: "025",
    name: "Pikachu",
    img: "/img/pikachu.png",
    type1: "Electric",
    type2: "",
    weight: "6,0 kg",
    height: "0,4 m",
    ability1: "Mega-Punch",
    ability2: "Pay-Day",
    color1: "#F9CF30",
    color2: "",
    description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    stats: {
      HP: "035",
      ATK: "055",
      DEF: "040",
      SATK: "050",
      SDEF: "050",
      SPD: "090",
    },
  },
  {
    id: "152",
    name: "Mew",
    img: "/img/mew.png",
    type1: "Psychic",
    type2: "",
    weight: "4,0 kg",
    height: "0,4 m",
    ability1: "Synchronize",
    ability2: "",
    color1: "#FB5584",
    color2: "",
    description:
      "When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.",
    stats: {
      HP: "100",
      ATK: "100",
      DEF: "100",
      SATK: "100",
      SDEF: "100",
      SPD: "100",
    },
  },
  {
    id: "092",
    name: "Gastly",
    img: "/img/gastly.png",
    type1: "Ghost",
    type2: "Poison",
    weight: "0,1 kg",
    height: "1,3 m",
    ability1: "Levitate",
    ability2: "",
    color1: "#70559B",
    color2: "#A43E9E",
    description:
      "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    stats: {
      HP: "030",
      ATK: "035",
      DEF: "030",
      SATK: "100",
      SDEF: "035",
      SPD: "080",
    },
  },
  {
    id: "132",
    name: "Ditto",
    img: "/img/ditto.png",
    type1: "Normal",
    type2: "",
    weight: "4,0 kg",
    height: "0,3 m",
    ability1: "Limber",
    ability2: "Imposter",
    color1: "#AAA67F",
    color2: "",
    description:
      "It can reconstritute its entire cellular structureto change into what it sees, but it returns to normal when it relaxes.",
    stats: {
      HP: "048",
      ATK: "048",
      DEF: "048",
      SATK: "048",
      SDEF: "048",
      SPD: "048",
    },
  },
  {
    id: "304",
    name: "Aron",
    img: "/img/aron.png",
    type1: "Steel",
    type2: "Rock",
    weight: "60,0 kg",
    height: "0,4 m",
    ability1: "Sturdy",
    ability2: "Rock-Head",
    color1: "#B7B9D0",
    color2: "#B69E31",
    description:
      "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    stats: {
      HP: "050",
      ATK: "070",
      DEF: "100",
      SATK: "040",
      SDEF: "040",
      SPD: "030",
    },
  },
];

export default data;
